"""Add description and updated_at to households

Revision ID: 1238702f085a
Revises: a0986ca31e7a
Create Date: 2025-08-24 12:17:29.509321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1238702f085a'
down_revision = 'a0986ca31e7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_members', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('household_members', 'invited_at')
    op.add_column('households', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('households', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('households', 'updated_at')
    op.drop_column('households', 'description')
    op.add_column('household_members', sa.Column('invited_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('household_members', 'joined_at')
    # ### end Alembic commands ###
