"""Add name field to tags table

Revision ID: 8dfdd837bb90
Revises: 1238702f085a
Create Date: 2025-08-24 14:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfdd837bb90'
down_revision = '1238702f085a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(), nullable=True))
    op.add_column('tags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_household_tag_name_norm', 'tags', ['household_id', 'name_norm'])
    
    # Update existing records to set name = name_norm as a temporary fix
    op.execute("UPDATE tags SET name = name_norm WHERE name IS NULL")
    
    # Make name column non-nullable after setting values
    op.alter_column('tags', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_household_tag_name_norm', 'tags', type_='unique')
    op.drop_column('tags', 'created_at')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###